### ISSUE TITLE
Module does not update info

### ISSUE THREAD

**Issue by Egorarchitec** [sheyabernstein/MMM-pihole-stats#10]
Hi! I have an issue with a module. It doesn't update info. It pulls it on initial load, and then nothing. I was trying different update Intervals, but nothing works..

**Comment by Kandr0s** [comment]
Yesterday, I noticed this issue as well.
The function `scheduleUpdate()` is never called again

https://github.com/sheyabernstein/MMM-pihole-stats/blob/master/MMM-pihole-stats.js#L132
The Timeout function needs `scheduleUpdate(this.config.updateInterval);` as well.

**Comment by Egorarchitec** [comment]
Chmm. Added this line, so that part of the code looks like this now 
``` 
scheduleUpdate: function (delay) {
                var nextLoad = this.config.updateInterval;
                if (typeof delay !== 'undefined' && delay >= 0) {
                        nextLoad = delay;
                }

                var self = this;
                setTimeout(function () {
                        self.updateStats();
                        scheduleUpdate(this.config.updateInterval);
                }, nextLoad);
        },
```

But module still doesn't update stats..

**Comment by Kandr0s** [comment]
you are missing a `self.`, sry.

```
setTimeout(function () {
        self.updateStats();
        self.scheduleUpdate(this.config.updateInterval);
}, nextLoad);
```

That should do the work.

**Comment by Egorarchitec** [comment]
Great! It works now! Thanks for your help!

**Comment by zanix** [comment]
This is sort of my bad, I re-did the fetch code and I skipped over this.
I also stopped using Pi-Hole so I never caught it.
Thanks for the fix, I also created a PR for it #14

**Comment by ProfessorShroom** [comment]
I'm having this same issue, any ideas as it looks like that fix has been applied already

**Comment by sheyabernstein** [comment]
Hi @charliehoward , this was fixed in pr #14

**Comment by ProfessorShroom** [comment]
But it's not fixed for me, I've checked the code to make sure it's the same as the fix and it is but it isn't updating
